/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ArticlesRouteRouteImport } from './routes/articles/route'
import { Route as CartRouteRouteImport } from './routes/cart/route'
import { Route as CheckoutRouteRouteImport } from './routes/checkout/route'
import { Route as CourierRouteRouteImport } from './routes/courier/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as GalleryRouteRouteImport } from './routes/gallery/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles/$articleId'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as AdminAdminsIndexRouteImport } from './routes/admin/admins/index'
import { Route as AdminAdminsAdminIdRouteImport } from './routes/admin/admins/$adminId'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin/articles/index'
import { Route as AdminArticlesNewRouteImport } from './routes/admin/articles/new'
import { Route as AdminCouponsIndexRouteImport } from './routes/admin/coupons/index'
import { Route as AdminCouriersIndexRouteImport } from './routes/admin/couriers/index'
import { Route as AdminCouriersCourierIdRouteImport } from './routes/admin/couriers/$courierId'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminReviewsIndexRouteImport } from './routes/admin/reviews/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as CourierScanOrderIdRouteImport } from './routes/courier/scan/$orderId'
import { Route as DashboardAddressesIndexRouteImport } from './routes/dashboard/addresses/index'
import { Route as DashboardInfoIndexRouteImport } from './routes/dashboard/info/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardOrdersOrderIdRouteImport } from './routes/dashboard/orders/$orderId'
import { Route as DashboardWalletIndexRouteImport } from './routes/dashboard/wallet/index'
import { Route as AdminAdmin2DashboardIndexRouteImport } from './routes/admin/admin2/dashboard/index'
import { Route as AdminAdmin2LiveOrdersIndexRouteImport } from './routes/admin/admin2/live-orders/index'
import { Route as AdminArticlesArticleIdEditRouteImport } from './routes/admin/articles/$articleId/edit'
import { Route as AdminOrdersOrderIdIndexRouteImport } from './routes/admin/orders/$orderId/index'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/admin/products/$productId/edit'
import { Route as AdminUsersUserIdIndexRouteImport } from './routes/admin/users/$userId/index'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/admin/users/$userId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRouteRoute = ArticlesRouteRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRouteRoute = CartRouteRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRouteRoute = CourierRouteRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRouteRoute = GalleryRouteRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRouteRoute,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => ArticlesRouteRoute,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CartRouteRoute,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRouteRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const AdminAdminsIndexRoute = AdminAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminsAdminIdRoute = AdminAdminsAdminIdRouteImport.update({
  id: '/admins/$adminId',
  path: '/admins/$adminId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCouponsIndexRoute = AdminCouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCouriersIndexRoute = AdminCouriersIndexRouteImport.update({
  id: '/couriers/',
  path: '/couriers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCouriersCourierIdRoute = AdminCouriersCourierIdRouteImport.update({
  id: '/couriers/$courierId',
  path: '/couriers/$courierId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CourierScanOrderIdRoute = CourierScanOrderIdRouteImport.update({
  id: '/scan/$orderId',
  path: '/scan/$orderId',
  getParentRoute: () => CourierRouteRoute,
} as any)
const DashboardAddressesIndexRoute = DashboardAddressesIndexRouteImport.update({
  id: '/addresses/',
  path: '/addresses/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInfoIndexRoute = DashboardInfoIndexRouteImport.update({
  id: '/info/',
  path: '/info/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersOrderIdRoute = DashboardOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWalletIndexRoute = DashboardWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminAdmin2DashboardIndexRoute =
  AdminAdmin2DashboardIndexRouteImport.update({
    id: '/admin2/dashboard/',
    path: '/admin2/dashboard/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdmin2LiveOrdersIndexRoute =
  AdminAdmin2LiveOrdersIndexRouteImport.update({
    id: '/admin2/live-orders/',
    path: '/admin2/live-orders/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminArticlesArticleIdEditRoute =
  AdminArticlesArticleIdEditRouteImport.update({
    id: '/articles/$articleId/edit',
    path: '/articles/$articleId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOrdersOrderIdIndexRoute = AdminOrdersOrderIdIndexRouteImport.update({
  id: '/orders/$orderId/',
  path: '/orders/$orderId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/articles': typeof ArticlesRouteRouteWithChildren
  '/cart': typeof CartRouteRouteWithChildren
  '/checkout': typeof CheckoutRouteRouteWithChildren
  '/courier': typeof CourierRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/gallery': typeof GalleryRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/admins/$adminId': typeof AdminAdminsAdminIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/couriers/$courierId': typeof AdminCouriersCourierIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/courier/scan/$orderId': typeof CourierScanOrderIdRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdRoute
  '/admin/admins/': typeof AdminAdminsIndexRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/coupons/': typeof AdminCouponsIndexRoute
  '/admin/couriers/': typeof AdminCouriersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/dashboard/addresses/': typeof DashboardAddressesIndexRoute
  '/dashboard/info/': typeof DashboardInfoIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/wallet/': typeof DashboardWalletIndexRoute
  '/admin/articles/$articleId/edit': typeof AdminArticlesArticleIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/admin2/dashboard/': typeof AdminAdmin2DashboardIndexRoute
  '/admin/admin2/live-orders/': typeof AdminAdmin2LiveOrdersIndexRoute
  '/admin/orders/$orderId/': typeof AdminOrdersOrderIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courier': typeof CourierRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/admins/$adminId': typeof AdminAdminsAdminIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/couriers/$courierId': typeof AdminCouriersCourierIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/courier/scan/$orderId': typeof CourierScanOrderIdRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdRoute
  '/admin/admins': typeof AdminAdminsIndexRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/coupons': typeof AdminCouponsIndexRoute
  '/admin/couriers': typeof AdminCouriersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/dashboard/addresses': typeof DashboardAddressesIndexRoute
  '/dashboard/info': typeof DashboardInfoIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/wallet': typeof DashboardWalletIndexRoute
  '/admin/articles/$articleId/edit': typeof AdminArticlesArticleIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/admin2/dashboard': typeof AdminAdmin2DashboardIndexRoute
  '/admin/admin2/live-orders': typeof AdminAdmin2LiveOrdersIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/articles': typeof ArticlesRouteRouteWithChildren
  '/cart': typeof CartRouteRouteWithChildren
  '/checkout': typeof CheckoutRouteRouteWithChildren
  '/courier': typeof CourierRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/gallery': typeof GalleryRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/admins/$adminId': typeof AdminAdminsAdminIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/couriers/$courierId': typeof AdminCouriersCourierIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/courier/scan/$orderId': typeof CourierScanOrderIdRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdRoute
  '/admin/admins/': typeof AdminAdminsIndexRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/coupons/': typeof AdminCouponsIndexRoute
  '/admin/couriers/': typeof AdminCouriersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/dashboard/addresses/': typeof DashboardAddressesIndexRoute
  '/dashboard/info/': typeof DashboardInfoIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/wallet/': typeof DashboardWalletIndexRoute
  '/admin/articles/$articleId/edit': typeof AdminArticlesArticleIdEditRoute
  '/admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/admin2/dashboard/': typeof AdminAdmin2DashboardIndexRoute
  '/admin/admin2/live-orders/': typeof AdminAdmin2LiveOrdersIndexRoute
  '/admin/orders/$orderId/': typeof AdminOrdersOrderIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/cart'
    | '/checkout'
    | '/courier'
    | '/dashboard'
    | '/gallery'
    | '/products'
    | '/login'
    | '/articles/$articleId'
    | '/products/$productId'
    | '/about/'
    | '/admin/'
    | '/articles/'
    | '/cart/'
    | '/checkout/'
    | '/dashboard/'
    | '/gallery/'
    | '/products/'
    | '/admin/admins/$adminId'
    | '/admin/articles/new'
    | '/admin/couriers/$courierId'
    | '/admin/products/new'
    | '/courier/scan/$orderId'
    | '/dashboard/orders/$orderId'
    | '/admin/admins/'
    | '/admin/articles/'
    | '/admin/coupons/'
    | '/admin/couriers/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/reviews/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/dashboard/addresses/'
    | '/dashboard/info/'
    | '/dashboard/orders/'
    | '/dashboard/wallet/'
    | '/admin/articles/$articleId/edit'
    | '/admin/products/$productId/edit'
    | '/admin/users/$userId/edit'
    | '/admin/admin2/dashboard/'
    | '/admin/admin2/live-orders/'
    | '/admin/orders/$orderId/'
    | '/admin/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courier'
    | '/login'
    | '/articles/$articleId'
    | '/products/$productId'
    | '/about'
    | '/admin'
    | '/articles'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/gallery'
    | '/products'
    | '/admin/admins/$adminId'
    | '/admin/articles/new'
    | '/admin/couriers/$courierId'
    | '/admin/products/new'
    | '/courier/scan/$orderId'
    | '/dashboard/orders/$orderId'
    | '/admin/admins'
    | '/admin/articles'
    | '/admin/coupons'
    | '/admin/couriers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/addresses'
    | '/dashboard/info'
    | '/dashboard/orders'
    | '/dashboard/wallet'
    | '/admin/articles/$articleId/edit'
    | '/admin/products/$productId/edit'
    | '/admin/users/$userId/edit'
    | '/admin/admin2/dashboard'
    | '/admin/admin2/live-orders'
    | '/admin/orders/$orderId'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/cart'
    | '/checkout'
    | '/courier'
    | '/dashboard'
    | '/gallery'
    | '/products'
    | '/login'
    | '/articles/$articleId'
    | '/products/$productId'
    | '/about/'
    | '/admin/'
    | '/articles/'
    | '/cart/'
    | '/checkout/'
    | '/dashboard/'
    | '/gallery/'
    | '/products/'
    | '/admin/admins/$adminId'
    | '/admin/articles/new'
    | '/admin/couriers/$courierId'
    | '/admin/products/new'
    | '/courier/scan/$orderId'
    | '/dashboard/orders/$orderId'
    | '/admin/admins/'
    | '/admin/articles/'
    | '/admin/coupons/'
    | '/admin/couriers/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/reviews/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/dashboard/addresses/'
    | '/dashboard/info/'
    | '/dashboard/orders/'
    | '/dashboard/wallet/'
    | '/admin/articles/$articleId/edit'
    | '/admin/products/$productId/edit'
    | '/admin/users/$userId/edit'
    | '/admin/admin2/dashboard/'
    | '/admin/admin2/live-orders/'
    | '/admin/orders/$orderId/'
    | '/admin/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRouteRoute: typeof AboutRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ArticlesRouteRoute: typeof ArticlesRouteRouteWithChildren
  CartRouteRoute: typeof CartRouteRouteWithChildren
  CheckoutRouteRoute: typeof CheckoutRouteRouteWithChildren
  CourierRouteRoute: typeof CourierRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  GalleryRouteRoute: typeof GalleryRouteRouteWithChildren
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRouteRoute
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof ArticlesRouteRoute
    }
    '/cart/': {
      id: '/cart/'
      path: '/'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof CartRouteRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRouteRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/admin/admins/': {
      id: '/admin/admins/'
      path: '/admins'
      fullPath: '/admin/admins/'
      preLoaderRoute: typeof AdminAdminsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/admins/$adminId': {
      id: '/admin/admins/$adminId'
      path: '/admins/$adminId'
      fullPath: '/admin/admins/$adminId'
      preLoaderRoute: typeof AdminAdminsAdminIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/coupons/': {
      id: '/admin/coupons/'
      path: '/coupons'
      fullPath: '/admin/coupons/'
      preLoaderRoute: typeof AdminCouponsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/couriers/': {
      id: '/admin/couriers/'
      path: '/couriers'
      fullPath: '/admin/couriers/'
      preLoaderRoute: typeof AdminCouriersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/couriers/$courierId': {
      id: '/admin/couriers/$courierId'
      path: '/couriers/$courierId'
      fullPath: '/admin/couriers/$courierId'
      preLoaderRoute: typeof AdminCouriersCourierIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/reviews'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/courier/scan/$orderId': {
      id: '/courier/scan/$orderId'
      path: '/scan/$orderId'
      fullPath: '/courier/scan/$orderId'
      preLoaderRoute: typeof CourierScanOrderIdRouteImport
      parentRoute: typeof CourierRouteRoute
    }
    '/dashboard/addresses/': {
      id: '/dashboard/addresses/'
      path: '/addresses'
      fullPath: '/dashboard/addresses/'
      preLoaderRoute: typeof DashboardAddressesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/info/': {
      id: '/dashboard/info/'
      path: '/info'
      fullPath: '/dashboard/info/'
      preLoaderRoute: typeof DashboardInfoIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/$orderId': {
      id: '/dashboard/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId'
      preLoaderRoute: typeof DashboardOrdersOrderIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wallet/': {
      id: '/dashboard/wallet/'
      path: '/wallet'
      fullPath: '/dashboard/wallet/'
      preLoaderRoute: typeof DashboardWalletIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/admin2/dashboard/': {
      id: '/admin/admin2/dashboard/'
      path: '/admin2/dashboard'
      fullPath: '/admin/admin2/dashboard/'
      preLoaderRoute: typeof AdminAdmin2DashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/admin2/live-orders/': {
      id: '/admin/admin2/live-orders/'
      path: '/admin2/live-orders'
      fullPath: '/admin/admin2/live-orders/'
      preLoaderRoute: typeof AdminAdmin2LiveOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/articles/$articleId/edit': {
      id: '/admin/articles/$articleId/edit'
      path: '/articles/$articleId/edit'
      fullPath: '/admin/articles/$articleId/edit'
      preLoaderRoute: typeof AdminArticlesArticleIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/$orderId/': {
      id: '/admin/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId/'
      preLoaderRoute: typeof AdminOrdersOrderIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/$productId/edit': {
      id: '/admin/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId/': {
      id: '/admin/users/$userId/'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AdminUsersUserIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId/edit': {
      id: '/admin/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AboutRouteRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteRouteChildren: AboutRouteRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteRouteWithChildren = AboutRouteRoute._addFileChildren(
  AboutRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdminsAdminIdRoute: typeof AdminAdminsAdminIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminCouriersCourierIdRoute: typeof AdminCouriersCourierIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminAdminsIndexRoute: typeof AdminAdminsIndexRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminCouponsIndexRoute: typeof AdminCouponsIndexRoute
  AdminCouriersIndexRoute: typeof AdminCouriersIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminArticlesArticleIdEditRoute: typeof AdminArticlesArticleIdEditRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRoute
  AdminAdmin2DashboardIndexRoute: typeof AdminAdmin2DashboardIndexRoute
  AdminAdmin2LiveOrdersIndexRoute: typeof AdminAdmin2LiveOrdersIndexRoute
  AdminOrdersOrderIdIndexRoute: typeof AdminOrdersOrderIdIndexRoute
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAdminsAdminIdRoute: AdminAdminsAdminIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminCouriersCourierIdRoute: AdminCouriersCourierIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminAdminsIndexRoute: AdminAdminsIndexRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminCouponsIndexRoute: AdminCouponsIndexRoute,
  AdminCouriersIndexRoute: AdminCouriersIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminArticlesArticleIdEditRoute: AdminArticlesArticleIdEditRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRoute,
  AdminAdmin2DashboardIndexRoute: AdminAdmin2DashboardIndexRoute,
  AdminAdmin2LiveOrdersIndexRoute: AdminAdmin2LiveOrdersIndexRoute,
  AdminOrdersOrderIdIndexRoute: AdminOrdersOrderIdIndexRoute,
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ArticlesRouteRouteChildren {
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteRouteChildren: ArticlesRouteRouteChildren = {
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteRouteWithChildren = ArticlesRouteRoute._addFileChildren(
  ArticlesRouteRouteChildren,
)

interface CartRouteRouteChildren {
  CartIndexRoute: typeof CartIndexRoute
}

const CartRouteRouteChildren: CartRouteRouteChildren = {
  CartIndexRoute: CartIndexRoute,
}

const CartRouteRouteWithChildren = CartRouteRoute._addFileChildren(
  CartRouteRouteChildren,
)

interface CheckoutRouteRouteChildren {
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteRouteChildren: CheckoutRouteRouteChildren = {
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteRouteWithChildren = CheckoutRouteRoute._addFileChildren(
  CheckoutRouteRouteChildren,
)

interface CourierRouteRouteChildren {
  CourierScanOrderIdRoute: typeof CourierScanOrderIdRoute
}

const CourierRouteRouteChildren: CourierRouteRouteChildren = {
  CourierScanOrderIdRoute: CourierScanOrderIdRoute,
}

const CourierRouteRouteWithChildren = CourierRouteRoute._addFileChildren(
  CourierRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOrdersOrderIdRoute: typeof DashboardOrdersOrderIdRoute
  DashboardAddressesIndexRoute: typeof DashboardAddressesIndexRoute
  DashboardInfoIndexRoute: typeof DashboardInfoIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardWalletIndexRoute: typeof DashboardWalletIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOrdersOrderIdRoute: DashboardOrdersOrderIdRoute,
  DashboardAddressesIndexRoute: DashboardAddressesIndexRoute,
  DashboardInfoIndexRoute: DashboardInfoIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardWalletIndexRoute: DashboardWalletIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface GalleryRouteRouteChildren {
  GalleryIndexRoute: typeof GalleryIndexRoute
}

const GalleryRouteRouteChildren: GalleryRouteRouteChildren = {
  GalleryIndexRoute: GalleryIndexRoute,
}

const GalleryRouteRouteWithChildren = GalleryRouteRoute._addFileChildren(
  GalleryRouteRouteChildren,
)

interface ProductsRouteRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRouteRoute: AboutRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ArticlesRouteRoute: ArticlesRouteRouteWithChildren,
  CartRouteRoute: CartRouteRouteWithChildren,
  CheckoutRouteRoute: CheckoutRouteRouteWithChildren,
  CourierRouteRoute: CourierRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  GalleryRouteRoute: GalleryRouteRouteWithChildren,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
